
Problem </pro>pb1_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb1_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb2_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb3_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb4_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb5_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb5_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb5_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb5_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb5_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb5_6</> solved by System </sys>2</> using planner </pla>2</>.
The solution of </pro>pb5_7</> is </sol>['move_to_box_a', 'move_to_box_c', 'signal_a_b', 'open_a', 'peek_c']</> with correctness </cor>0.6</> and has been found in </tim>10.294201612472534s</> by System </sys>1</> using mode </mod>5</>.
Problem </pro>pb5_8</> solved by System </sys>2</> using planner </pla>2</>.
The solution of </pro>pb5_9</> is </sol>['move_to_box_a', 'move_to_box_c', 'signal_a_b', 'open_a', 'peek_c']</> with correctness </cor>0.833333</> and has been found in </tim>9.72893476486206s</> by System </sys>1</> using mode </mod>5</>.
Problem </pro>pb5_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb6_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb7_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb8_8</> solved by System </sys>2</> using planner </pla>2</>.
The solution of </pro>pb8_9</> is </sol>['move_to_box_a', 'move_to_box_b', 'move_to_box_d']</> with correctness </cor>0.8</> and has been found in </tim>11.698524475097656s</> by System </sys>1</> using mode </mod>5</>.
Problem </pro>pb8_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb9_8</> solved by System </sys>2</> using planner </pla>2</>.
The solution of </pro>pb9_9</> is </sol>['move_to_box_d', 'move_to_box_b', 'move_to_box_e', 'signal_a_b', 'open_e']</> with correctness </cor>1.0</> and has been found in </tim>11.572540760040283s</> by System </sys>1</> using mode </mod>5</>.
Problem </pro>pb9_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb10_8</> solved by System </sys>2</> using planner </pla>2</>.
The solution of </pro>pb10_9</> is </sol>['move_to_box_b', 'move_to_box_d']</> with correctness </cor>0.8</> and has been found in </tim>8.63140082359314s</> by System </sys>1</> using mode </mod>5</>.
Problem </pro>pb10_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb11_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb12_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb13_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb14_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb15_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb16_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb17_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb18_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb19_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb20_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb21_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb22_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb23_10</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_1</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_2</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_3</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_4</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_5</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_6</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_7</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_8</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_9</> solved by System </sys>2</> using planner </pla>2</>.
Problem </pro>pb24_10</> solved by System </sys>2</> using planner </pla>2</>.
